name: build_countingbook_app

on: [push]

jobs:
  build_app:
    runs_on: ubuntu-latest
    steps:
    - id: s01
      run: echo "github ${{ github.ref_name}}"
    - id: s02
      uses: actions/setup-node@v4
      with:
        node-version: 24